artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://storage.googleapis.com/kaggle-data-sets/3579787/6358196/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20240725%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240725T193444Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=48607b389f22bdf7a23df1e9308e1234c012b52f816d8a368d29c16c8be052eb4ae72ea8228d518833b80ccf7e43bcd3bfbddf1e22a6fb51840b917cd03820d83772450dce8d5fa907834892ed67f8e5141efddf999a98ad6599df5df67388b330e8374db971a8b5dfb683d6c6ebc22bdf0e297f1552c036e496af7e542dfebbe5b5899cd8ba047d7254b3bffdc77f8adbea5b9e9a2a95afeff2eca3a61d162a096b92834b387b22d62d8bfc93d9f586214097ed233eee074fce9e8be13a934dc31bc7889acbbddece9b8ffc139d2d43160fe9d4dd8ee704403f2b7bf4c4516521368f4d799c8926debd56b3e089de75f4c0b3b1f57f16f66e15cbb0cae797e3
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/KAGGLE/AUDIO
  n_fft: 2048
  hop_length: 512
  n_mels: 128

data_validation:
  root_dir: artifacts/data_validation
  data_path: artifacts/data_transformation
  status_file: artifacts/data_validation/status.txt
  required_files: ['X_train.npy', 'X_test.npy', 'y_train.npy', 'y_test.npy']

model_preparation:
  root_dir: artifacts/model_preparation
  base_model_path: artifacts/model_preparation/base_model.keras
  updated_model_path: artifacts/model_preparation/updated_model.keras

callback_preparation:
  root_dir: artifacts/callback_preparation
  tensorboard_log_dir: artifacts/callback_preparation/tensorboard_log_dir
  model_checkpoint_dir: artifacts/callback_preparation/checkpoint_dir/model-{epoch:02d}-{val_loss:0.2f}.keras

model_training:
  root_dir: artifacts/model_training
  trained_model_dir: artifacts/model_training/model.keras

model_evaluation:
  root_dir: artifacts/model_evaluation
  evaluation_results_dir: artifacts/model_evaluation/evaluation_scores.json