artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://storage.googleapis.com/kaggle-data-sets/3579787/6358196/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20240427%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240427T022413Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=49ba18397faab95b2f21b745c5736168bb976a1205eddeb98dac1155e0621f48d9ea682a876638acb57914b3548b8ca1a66bb6b9fa59645b3b7cf2b8edf5716da58b539b7bc3758e859d16392f12b42033120f26dae572aafcfb1ce4ff806a94f0ca1fb3a9a21969675aeb2949636f4d442d8b7957152ccce7ccebe6cafe72f2a4ad35a499122bec90cca1706fb2ea1aa6a082a656ee46cb4d5c5a69ebbfac10e67b09613e4929e1a78c42fa3a05b21a844fcce815d617e69e7db864a31266566979f672d60f2f832ead06da41ad45b9c69652e78a3d5d7befdc1049cb56b803dd903c9336de08bf5f8be6181362dfff71fa11a8e419cac856eb1d37d88beb7c
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/KAGGLE/AUDIO
  n_fft: 2048
  hop_length: 512
  n_mels: 128

data_validation:
  root_dir: artifacts/data_validation
  data_path: artifacts/data_transformation
  status_file: artifacts/data_validation/status.txt
  required_files: ['X_train.npy', 'X_test.npy', 'y_train.npy', 'y_test.npy']

model_preparation:
  root_dir: artifacts/model_preparation
  base_model_path: artifacts/model_preparation/base_model.keras
  updated_model_path: artifacts/model_preparation/updated_model.keras

callback_preparation:
  root_dir: artifacts/callback_preparation
  tensorboard_log_dir: artifacts/callback_preparation/tensorboard_log_dir
  model_checkpoint_dir: artifacts/callback_preparation/checkpoint_dir/model-{epoch:02d}-{val_loss:0.2f}.keras

model_training:
  root_dir: artifacts/model_training
  trained_model_dir: artifacts/model_training/model.keras

model_evaluation:
  root_dir: artifacts/model_evaluation
  evaluation_results_dir: artifacts/model_evaluation/evaluation_scores.json