# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - audioclassification

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://audioclassification.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_19d44f9476a44bd4ac12e969f04d2a19 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_881b79b38e124ca88d493202d7f68eb0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: audioclassification.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_19d44f9476a44bd4ac12e969f04d2a19 }}/classifier:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'audioclassification'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7e8296347b1b4c84b6cb126f70b6bd44 }}
        images: 'audioclassification.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_19d44f9476a44bd4ac12e969f04d2a19 }}/classifier:${{ github.sha }}'